openapi: 3.0.1
info:
  title: Library Management API
  description: API documentation for the library management system
  version: 1.0.0
servers:
  - url: http://localhost:3000/api

paths:
  #Auth paths
  /auth/signup:
    $ref: './paths/auth.paths.yaml#/signup'
  /auth/request-email-verification:
    $ref: './paths/auth.paths.yaml#/request-email-verification'
  /auth/verify-email:
    $ref: './paths/auth.paths.yaml#/verify-email'
  /auth/login:
    $ref: './paths/auth.paths.yaml#/login'
  /auth/refresh-access-token:
    $ref: './paths/auth.paths.yaml#/refresh-access-token'

  #Book paths
  /books:
    $ref: './paths/book.paths.yaml#/books'
  /books/{bookId}:
    $ref: './paths/book.paths.yaml#/books{bookId}'
  /books/{bookId}/borrow:
    $ref: './paths/book.paths.yaml#/books{bookId}borrow'
  /books/{bookId}/borrowing-history:
    $ref: './paths/book.paths.yaml#/books{bookId}borrowing-history'
  /books/{bookId}/reservations:
    $ref: './paths/book.paths.yaml#/books{bookId}reservations'

  #User paths
  /users:
    $ref: './paths/user.paths.yaml#/users-profile'
  /users/borrowing-history:
    $ref: './paths/user.paths.yaml#/users-borrowing-history'
  /users/reservations:
    $ref: './paths/user.paths.yaml#/users-reservations'

  #Reservation paths
  /reservations/{reservationId}:
    $ref: './paths/reservation.paths.yaml#/reservations{reservationId}'
  /reservations/{reservationId}/claim:
    $ref: './paths/reservation.paths.yaml#/reservations{reservationId}claim'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
