openapi: 3.0.1
info:
  title: Library Management API
  description: API documentation for the library management system
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
  - url: https://library-management-system-s1x4.onrender.com/api

paths:
  #Auth paths
  /auth/signup:
    $ref: './paths/auth.paths.yaml#/signup'
  /auth/request-email-verification:
    $ref: './paths/auth.paths.yaml#/request-email-verification'
  /auth/verify-email:
    $ref: './paths/auth.paths.yaml#/verify-email'
  /auth/login:
    $ref: './paths/auth.paths.yaml#/login'
  /auth/refresh-access-token:
    $ref: './paths/auth.paths.yaml#/refresh-access-token'

  #Book paths
  /books:
    $ref: './paths/book.paths.yaml#/books'
  /books/{id}:
    $ref: './paths/book.paths.yaml#/books{id}'
  /books/{id}/borrow:
    $ref: './paths/book.paths.yaml#/books{id}borrow'
  /books/{id}/borrowing-history:
    $ref: './paths/book.paths.yaml#/books{id}borrowing-history'
  /books/{id}/reservations:
    $ref: './paths/book.paths.yaml#/books{id}reservations'

  #User paths
  /users/profile:
    $ref: './paths/user.paths.yaml#/users-profile'
  /users/borrowing-history:
    $ref: './paths/user.paths.yaml#/users-borrowing-history'
  /users/reservations:
    $ref: './paths/user.paths.yaml#/users-reservations'
  /users/fines:
    $ref: './paths/user.paths.yaml#/users-fines'

  #Reservation paths
  /reservations/{id}:
    $ref: './paths/reservation.paths.yaml#/reservations{id}'
  /reservations/{id}/claim:
    $ref: './paths/reservation.paths.yaml#/reservations{id}claim'

  #Borrowing paths
  /borrowings/{id}/renew:
    $ref: './paths/borrowing.paths.yaml#/renew-book'
  /borrowings/{id}/return:
    $ref: './paths/borrowing.paths.yaml#/return-book'
  /borrowings/{id}/report-lost:
    $ref: './paths/borrowing.paths.yaml#/report-lost'
  /borrowings/{id}/report-damaged:
    $ref: './paths/borrowing.paths.yaml#/report-damaged'

  #Fine paths
  /fines/{id}/initiate-payment:
    $ref: './paths/fine.paths.yaml#/initiate-payment'
  /fines/{id}:
    $ref: './paths/fine.paths.yaml#/get-fine'
  /fines/verify/{reference}:
    $ref: './paths/fine.paths.yaml#/verify-payment'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      $ref: './schemas.yaml#/User'
    Book:
      $ref: './schemas.yaml#/Book'
    Borrowing:
      $ref: './schemas.yaml#/Borrowing'
    Fine:
      $ref: './schemas.yaml#/Fine'
    Payment:
      $ref: './schemas.yaml#/Payment'
    Reservation:
      $ref: './schemas.yaml#/Reservation'
    Token:
      $ref: './schemas.yaml#/Token'
