- name: sort
  in: query
  description: Sort results by one or more fields. Use `-` for descending order.
  schema:
    type: string

- name: fields
  in: query
  description: Specify the fields to include or exclude. Use `-` to exclude fields.
  schema:
    type: string

- name: page
  in: query
  description: The page number of the results to retrieve.
  schema:
    type: integer
    default: 1
  example: 2

- name: limit
  in: query
  description: Limit the number of results returned per page.
  schema:
    type: integer
    default: 10
  example: 10
